### ISSUE TITLE
Vector sets

### ISSUE THREAD

**Issue by blegat** [darnstrom/DAQP.jl#5]
Note that you don't need to support vector functions and vector sets. If the user uses these then they will be bridged automatically into scalar functions and scalar sets if you solvers don't say that it supports it.
See https://jump.dev/MathOptInterface.jl/dev/submodules/Bridges/list_of_bridges/#MathOptInterface.Bridges.Constraint.ScalarizeBridge

**Comment by darnstrom** [comment]
Thanks for this comment! Support for vector sets was dropped in [10856a5](https://github.com/darnstrom/DAQP.jl/commit/10856a571ea8ecad583904b2984c3c7815597633) as a result and this made the MOI wrapper a lot cleaner!

**Comment by blegat** [comment]
Nice simplification indeed!
